### ISSUE TITLE
Node 7

### ISSUE THREAD

**Issue by GaryJones** [WordPress-Coding-Standards/stylelint-config-wordpress#142]
Can `package.json` add support for a node engine greater than 7?

**Comment by ntwb** [comment]
Travis CI uses [nvm](https://github.com/creationix/nvm) to manage and make easier the management of NodeJS versions, as such `7` is an _nvm alias_ for the latest NodeJS 7.x branch, currently that is `7.10.2` as can be seen [here](https://travis-ci.org/WordPress-Coding-Standards/stylelint-config-wordpress/jobs/235907706#L168).

**Comment by GaryJones** [comment]
My bad - I thought I my install of Yarn had also added node 7, but apparently I'm still on 6.2.2, so the error message is correct.
