### ISSUE TITLE
'Incorrect' peer dependency listed

### ISSUE THREAD

**Issue by tdmalone** [WordPress-Coding-Standards/stylelint-config-wordpress#173]
Yarn reports:

    warning "stylelint-config-wordpress@12.0.0" has incorrect peer dependency "stylelint@^7.10.1".

I'm not entirely sure though why it's an 'incorrect' dependency, as stylelint did indeed have a 7.10.1 version!

**Comment by WraithKenny** [comment]
stylelint is now on ^9.1.3

**Comment by WraithKenny** [comment]
additionally, stylelint-config-recommended is at ^2.1.0. 

The 1.0.0 has a peer of stylelint@8.0.0. 

the 2.1.0 version has a peer of `^8.3.0 || ^9.0.0`

Bumping these up in this repo would clear the unmet peer dependency warnings.

**Comment by WraithKenny** [comment]
bumbing stylelint to 9 worked fine, passed all test.

bumping stylelint-config-recommended to 2 failed a bunch of tests.

(unrelated, but, Updating eslint-plugin-wordpress broke jest.)

**Comment by ntwb** [comment]
I"ll fix this in the next couple of hours...

p.s. @WraithKenny `eslint-plugin-wordpress` has more explosions than just Jest, not advised to use it in its current state 😏

**Comment by ntwb** [comment]
Fixed in #188, will ship in `stylelint-config-wordpress` version `13.0.0` to be released momentarily...
