### ISSUE TITLE
Help me understand why function-url-quotes is set to 'never' ?

### ISSUE THREAD

**Issue by createandcode** [WordPress-Coding-Standards/stylelint-config-wordpress#205]
Hey,

Just getting going with stylelint - thanks for your work on the WP rules!

I'm curious about some of the rules you've set.

`'function-url-quotes': 'never',` means that I end up with tons of these:
![Unexpected quotes (function-url-quotes)](https://i.imgur.com/oEu8IlE.png)

`Unexpected quotes (function-url-quotes)`

This SO thread https://stackoverflow.com/a/2168861/22837 seems to lean towards using quotes.
I didn't see anything specific in the WP CSS coding guidelines in relation to this.

This one is also problematic for me:
`'font-family-name-quotes': 'always-where-recommended'`

Wikimedia had a debate on this and landed on `always-unless-keyword`
https://github.com/wikimedia/stylelint-config-wikimedia/issues/33

which would be what I would lean towards - again, WP guidelines seem non-existent for this too.

Would love to know the rationale for these decisions.

Thanks.

**Comment by GaryJones** [comment]
From https://make.wordpress.org/core/handbook/best-practices/coding-standards/css/#values:

> Use double quotes rather than single quotes, and only when needed, such as when a font name has a space or for the values of the content property.

... which then follows with an example snippet that contains:

```css
background-image: url(images/bg.png);
```

In this case, the paths to your font files do not contain a path, and therefore do not require quotes.

**Comment by createandcode** [comment]
@GaryJones - aha! I missed the "and only when needed" bit :)

Thanks!
