### ISSUE TITLE
support stylelint@11

### ISSUE THREAD

**Issue by jshwlkr** [WordPress-Coding-Standards/stylelint-config-wordpress#240]
I believe this would, at least, require both an update to `dependencies` and `peerDependencies`.  
  
https://github.com/WordPress-Coding-Standards/stylelint-config-wordpress/blob/master/package.json#L39  
https://github.com/WordPress-Coding-Standards/stylelint-config-wordpress/blob/master/package.json#L40  
https://github.com/WordPress-Coding-Standards/stylelint-config-wordpress/blob/master/package.json#L41  
https://github.com/WordPress-Coding-Standards/stylelint-config-wordpress/blob/master/package.json#L62 .

**Comment by ntwb** [comment]
Thanks for the reminder, I'll get this done soon

**Comment by ntwb** [comment]
Fixed via #234, will release a new version shortly
