### ISSUE TITLE
Is it possible to install stylelint + stylelint-config-wordpress globally?

### ISSUE THREAD

**Issue by cagross** [WordPress-Coding-Standards/stylelint-config-wordpress#243]
Hello.  Is it possible to install stylelint and stylelint-config-wordpress globally, and get them to work properly with VSCode in Windows?  If so, what are those instructions?

In a [previous issue](https://github.com/WordPress-Coding-Standards/stylelint-config-wordpress/issues/239), @ntwb helped me get stylelint and stylelint-config-wordpress working in VSCode, but on a project-by-project basis.  In that issue he mentioned:

> Installing stylelint (or many other similar tools, ESLint etc) globally is troublesome, primarily because if you swap repos, say from Twenty Twenty to Gutenberg the stylelint configurations are different, they are both based on `stylelint-config-wordpress` but have a few additional tweaks for each repo. Now if you add the `stylelint-config-wordpress` configuration globbaly then when you open either of those repos you will have conflicting stylelint configurations because you've installed `stylelint-config-wordpress` globally and the VSCode extension will not be able to know which config to use.

I see how having multiple projects with different stylelint configurations would cause issues.  But what if I ensured none of my projects had an existing stylelint configuration?  Would that then allow me to get stylelint and stylelint-config-wordpress working with VSCode globally?  If not, I can continue to work on a project-by-project basis.  But it would just be a little more time consuming on my end--I would prefer a global solution if possible.

Thanks.

**Comment by ntwb** [comment]
Thanks, but currently it is not, as evidenced by our previous discussion.

The primary reason is the VS Code Stylelint Extension doesn't support global installs.

**Comment by cagross** [comment]
@ntwb OK thanks for confirming, and no worries--I can continue to work on a project-by-project basis.  I appreciate your assistance with that--it will be a big help for me moving forward.

> The primary reason is the VS Code Stylelint Extension doesn't support global installs.

Just so I understand, is this to say that the VSCode stylelint extension cannot be installed globally?  Or is this to say that the VSCode stylelint extension does not recognize shareable configs that are installed globally?  Or something else?

**Comment by ntwb** [comment]
> Or is this to say that the VSCode stylelint extension does not recognize shareable configs that are installed globally?

This

**Comment by cagross** [comment]
OK thanks for that.
