### ISSUE TITLE
selector-class-pattern breaks with Gutenberg classes

### ISSUE THREAD

**Issue by juliquiron** [WordPress-Coding-Standards/stylelint-config-wordpress#253]
Hi there!

The new rule introduced for `selector-class-pattern` (see: https://github.com/WordPress-Coding-Standards/stylelint-config-wordpress/issues/236 and https://github.com/WordPress-Coding-Standards/stylelint-config-wordpress/pull/247/files) is marking as wrong some of the default classes of the core components of Gutenberg. 

This is because is considering wrong the modification for elements in the BEM style like `block-class-name__element`.

The example I found is with the class: `.wp-block-media-text__content`.

Is it really an issue or am I missing something?

thanks a lot for your work in the stylelint rules! :tada:

**Comment by ntwb** [comment]
Thanks @juliquiron, can you drop a link to the Gutenberg PR or Issue if one exists please, I've got some more updates for this in G'berg I hoping to push up this weekend and will take a closer look at this

**Comment by juliquiron** [comment]
AFAIK no PR or Issue in Gutenberg,sorry

**Comment by ntwb** [comment]
Thanks, I'll get some tests added and check Gutenberg also at the same time

**Comment by ntwb** [comment]
Closing this issue as this repo and project are merging into Gutenberg, see [#22777](https://github.com/WordPress/gutenberg/pull/22777)
